CREATE USER IF NOT EXISTS `8466075`@`localhost` IDENTIFIED WITH mysql_native_password BY '8T0s:Wo.zCYV{y4F';
GRANT SELECT,INSERT,DELETE,UPDATE,CREATE on `RMmain`.* TO `8466075`@`localhost`;

CREATE USER IF NOT EXISTS `87223298`@`localhost` IDENTIFIED WITH mysql_native_password BY '/1a9YLJ>Q+rNd.YQ';
GRANT SELECT,INSERT,DELETE,UPDATE on `RMlog`.* TO `87223298`@`localhost`;